package Telas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Conexao.DataBase;
import Conexao.DataBasePG;
import Metodos.NOcorrencias;
import Atributos.EOcorrencia;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.PreparedStatement;
import java.util.HashMap;
import javax.swing.border.LineBorder;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jefersonrodrigues
 */
public class TelaPesquisaInt extends javax.swing.JFrame {

    Statement statementSS, statementPG;
    DataBase db = new DataBase();
    DataBasePG db2 = new DataBasePG();
    Connection con = db.getCon();
    Connection con2 = db2.getCon();
    PreparedStatement PS;

    Vector<String> listaLimpa = new Vector<>();

    private EOcorrencia eOcorrencia = null;
    private NOcorrencias nOcorrencias = new NOcorrencias();

    /**
     * Creates new form TelaOcorrencia
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public TelaPesquisaInt() throws ClassNotFoundException, SQLException {
        initComponents();
//        carregaId();
//        idCampo.setEnabled(true);
        statementSS = con.createStatement();
        statementPG = con2.createStatement();
//        URL caminhoIcone = getClass().getResource("/Imagens/logoIcone.png");
//        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
//        this.setIconImage(iconeTitulo);

//        statement = con2.createStatement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        campoPesquisa = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaComunicante = new javax.swing.JList<>();
        idCampo = new javax.swing.JTextField();
        categoriaCampo = new javax.swing.JTextField();
        nomeCampo = new javax.swing.JTextField();
        comboOcorrencia = new javax.swing.JComboBox<>();
        dataCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            dataCampo = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        regCampo = new javax.swing.JTextField();
        conclusaoCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            conclusaoCampo = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        comunicanteCampo = new javax.swing.JTextField();
        celularCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##) # ####-####");
            celularCampo = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        fixoCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##) ####-####");
            fixoCampo = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        emailCampo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        relatoCampo = new javax.swing.JTextArea();
        relatoCampo.setLineWrap(true);
        jScrollPane2 = new javax.swing.JScrollPane();
        comentarioCampo = new javax.swing.JTextArea();
        comentarioCampo.setLineWrap(true);
        jScrollPane3 = new javax.swing.JScrollPane();
        providenciaCampo = new javax.swing.JTextArea();
        providenciaCampo.setLineWrap(true);
        destinatarioCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##) ####-####");
            fixoCampo = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        comboStatus = new javax.swing.JComboBox<>();
        botaoSalvar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoImprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PESQUISA DE OCORRÊNCIAS EXTERNAS");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setText("Pesquisa de Ocorrências");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nº Ocorrência:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Comunicante:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Paciente / ID:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Telefone Cel:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Telefone Fixo:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Data:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Data para Conclusão:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("E-mail:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Relato:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Tipo de Ocorrência:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Comentário:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Registro:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Status:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Providência:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Destinatário:");

        campoPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoPesquisa.setToolTipText("");
        campoPesquisa.setName(""); // NOI18N
        campoPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPesquisaMouseClicked(evt);
            }
        });
        campoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisaActionPerformed(evt);
            }
        });
        campoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPesquisaKeyReleased(evt);
            }
        });

        ListaComunicante.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "", "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaComunicante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaComunicanteMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(ListaComunicante);

        idCampo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idCampo.setEnabled(false);
        idCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCampoActionPerformed(evt);
            }
        });

        categoriaCampo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        categoriaCampo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        categoriaCampo.setEnabled(false);

        nomeCampo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeCampo.setEnabled(false);
        nomeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCampoActionPerformed(evt);
            }
        });

        comboOcorrencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "DENÚNCIA", "ELOGIO", "IMPROCEDENTE", "RECLAMAÇÃO", "SUGESTÃO" }));
        comboOcorrencia.setEnabled(false);
        comboOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOcorrenciaActionPerformed(evt);
            }
        });

        dataCampo.setToolTipText("");
        dataCampo.setEnabled(false);
        dataCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCampoActionPerformed(evt);
            }
        });

        regCampo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        regCampo.setEnabled(false);
        regCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCampoActionPerformed(evt);
            }
        });

        conclusaoCampo.setEnabled(false);
        conclusaoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclusaoCampoActionPerformed(evt);
            }
        });

        comunicanteCampo.setEnabled(false);
        comunicanteCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comunicanteCampoActionPerformed(evt);
            }
        });

        celularCampo.setEnabled(false);
        celularCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularCampoActionPerformed(evt);
            }
        });

        fixoCampo.setEnabled(false);
        fixoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixoCampoActionPerformed(evt);
            }
        });

        emailCampo.setEnabled(false);
        emailCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCampoActionPerformed(evt);
            }
        });

        relatoCampo.setColumns(10);
        relatoCampo.setRows(5);
        relatoCampo.setEnabled(false);
        jScrollPane1.setViewportView(relatoCampo);

        comentarioCampo.setColumns(10);
        comentarioCampo.setRows(5);
        comentarioCampo.setEnabled(false);
        jScrollPane2.setViewportView(comentarioCampo);

        providenciaCampo.setColumns(10);
        providenciaCampo.setRows(5);
        providenciaCampo.setEnabled(false);
        jScrollPane3.setViewportView(providenciaCampo);

        destinatarioCampo.setEnabled(false);
        destinatarioCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinatarioCampoActionPerformed(evt);
            }
        });

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "EM ANÁLISE", "ENCERRADO", "ENCAMINHADO", "PENDENTE" }));
        comboStatus.setEnabled(false);
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        botaoSalvar.setText("SALVAR");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        botaoAlterar.setText("ALTERAR");
        botaoAlterar.setEnabled(false);
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/apagar.png"))); // NOI18N
        botaoExcluir.setText("EXCLUIR");
        botaoExcluir.setEnabled(false);
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/limpar.png"))); // NOI18N
        botaoLimpar.setText("LIMPAR");
        botaoLimpar.setEnabled(false);
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        botaoVoltar.setText("VOLTAR");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imprimir.png"))); // NOI18N
        botaoImprimir.setText("IMPRIMIR");
        botaoImprimir.setEnabled(false);
        botaoImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImprimirActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logovh.png"))); // NOI18N

        jLabel18.setText("Digite o nome do Comunicante que deseja pesquisar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idCampo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(emailCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(celularCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(161, 161, 161)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fixoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comunicanteCampo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeCampo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(comboOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(regCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(165, 165, 165)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dataCampo)
                                .addComponent(conclusaoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2)
                    .addComponent(jLabel18))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(destinatarioCampo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15))
                                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(botaoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoImprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoriaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conclusaoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(comunicanteCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(celularCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fixoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinatarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comunicanteCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comunicanteCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comunicanteCampoActionPerformed

    private void nomeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCampoActionPerformed

    private void celularCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularCampoActionPerformed

    private void fixoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fixoCampoActionPerformed

    private void dataCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCampoActionPerformed

    private void conclusaoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclusaoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conclusaoCampoActionPerformed

    private void emailCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCampoActionPerformed

    private void comboOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOcorrenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOcorrenciaActionPerformed

    private void idCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCampoActionPerformed

    private void regCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regCampoActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
       try {
            if (validarCampos()) {
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisaExt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPesquisaExt.class.getName()).log(Level.SEVERE, null, ex);
        }
        limparCampos();
        desabilitarCampos();
        botaoSalvar.setEnabled(false);
        botaoAlterar.setEnabled(false);
        botaoExcluir.setEnabled(false);
        botaoImprimir.setEnabled(false);
        botaoLimpar.setEnabled(false);

    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        excluirOcorrencia();
        limparCampos();

    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void ListaComunicanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaComunicanteMouseClicked
        if (campoPesquisa.getText().isEmpty()) {

        } else {
            idCampo.setText(ListaComunicante.getSelectedValue().split(" - ")[0]);
        }
        try {
            buscarDados();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisaInt.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListaComunicante.setListData(listaLimpa);
        campoPesquisa.setText("");
        botaoAlterar.setEnabled(true);
        botaoImprimir.setEnabled(true);
        botaoVoltar.setEnabled(true);
        botaoLimpar.setEnabled(true);

    }//GEN-LAST:event_ListaComunicanteMouseClicked

    private void campoPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisaKeyReleased
        try {
            buscaComunicante();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_campoPesquisaKeyReleased

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        habilitarCampos();
        regCampo.setEnabled(false);
        nomeCampo.setEnabled(false);
        dataCampo.setEnabled(false);
        idCampo.setEnabled(false);
        botaoSalvar.setEnabled(true);

    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        TelaInicial tela = null;
        try {
            tela = new TelaInicial();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPesquisaInt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisaInt.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        limparCampos();
        desabilitarCampos();
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void destinatarioCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinatarioCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinatarioCampoActionPerformed

    private void botaoImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImprimirActionPerformed
        try {
            PS = con2.prepareStatement("SELECT * from OCORRENCIA_ WHERE id = '" + idCampo.getText() + "'");
//                + "' AND TIPO_OCORRENCIA = '"
//                + comboOcorrencia.getSelectedItem() + "' AND STATUS = '" + comboStatus.getSelectedItem() +
//                "' AND DATA BETWEEN '" + dataCampo.getText() + "' AND '" + dataCampo1.getText() + "' ORDER BY ID");
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisaInt.class.getName()).log(Level.SEVERE, null, ex);
        }

        ResultSet rs = null;
        try {
            rs = PS.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisaInt.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            if (rs.isBeforeFirst()) {
                JRResultSetDataSource teste = new JRResultSetDataSource(rs);
                String src = "impressaoSiouv.jasper";

                JasperPrint jaspertPrint = null;
                try {
                    jaspertPrint = JasperFillManager.fillReport(src, new HashMap(), teste);
                } catch (JRException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }

                JasperViewer view = new JasperViewer(jaspertPrint, false);

                view.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "erro!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisaInt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoImprimirActionPerformed

    private void campoPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPesquisaMouseClicked
        campoPesquisa.setText("");
        campoPesquisa.setForeground(Color.BLACK);

    }//GEN-LAST:event_campoPesquisaMouseClicked

    private void campoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesquisaActionPerformed

    private void buscaComunicante() throws SQLException {
        ListaComunicante.setListData(listaLimpa);
        if (campoPesquisa.getText().isEmpty()) {
//           
        } else {
            String queryString = "SELECT * from OCORRENCIA_ WHERE comunicante LIKE '%" + campoPesquisa.getText().toUpperCase() + "%'" + "AND CATEGORIA = 'INTERNA'";
            ResultSet rs = statementPG.executeQuery(queryString);
            Vector<String> listModel = new Vector<>(10);
            if (rs.next()) {
                do {
                    listModel.add(rs.getString(5) + "  -  " + rs.getString(9) + "  -  " + rs.getString(16));
//                            + "  -  "+ rs.getString(3).trim());
//                     +"  -  "+ rs.getString(4).trim() +"  -  "+ rs.getString(5).trim() +"  -  "+ rs.getString(6).trim()
//                     +"  -  "+ rs.getString(7).trim() +"  -  "+ rs.getString(8).trim() +"  -  "+ rs.getString(9).trim()
//                     +"  -  "+ rs.getString(10).trim() +"  -  "+ rs.getString(11).trim() +"  -  "+ rs.getString(12).trim()
//                     +"  -  "+ rs.getString(13).trim() +"  -  "+ rs.getString(14).trim());
                } while (rs.next());
            }
            ListaComunicante.setListData(listModel);

        }

    }
    
    public boolean validarCampos() throws SQLException, ClassNotFoundException {
        if (dataCampo.getText().equals("  /  /    ")){
            dataCampo.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Preencha o Campo Obrigatório!");
            return true;
        } else if (conclusaoCampo.getText().equals("  /  /    ")){
            dataCampo.setBorder(new LineBorder(Color.GRAY));
            conclusaoCampo.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Preencha o Campo Obrigatório!");
            return true;
        }else{
//            dataCampo.setBorder(new LineBorder(Color.GRAY));
            conclusaoCampo.setBorder(new LineBorder(Color.GRAY));
            alteraOcorrencia();
            return false;
        }
    }

    private void alteraOcorrencia() {
        eOcorrencia = new EOcorrencia();
        eOcorrencia.setRegistro(regCampo.getText());
        eOcorrencia.setPaciente(nomeCampo.getText());
        eOcorrencia.setOcorrencia((String) comboOcorrencia.getSelectedItem());
        eOcorrencia.setData(dataCampo.getText().substring(6, 10)+"-"+dataCampo.getText().substring(3, 5)+"-"+dataCampo.getText().substring(0, 2));
        eOcorrencia.setId(idCampo.getText());
        eOcorrencia.setConclusao(conclusaoCampo.getText().substring(6, 10)+"-"+conclusaoCampo.getText().substring(3, 5)+"-"+conclusaoCampo.getText().substring(0, 2));
        eOcorrencia.setCelular(celularCampo.getText());
        eOcorrencia.setFixo(fixoCampo.getText());
        eOcorrencia.setComunicante(comunicanteCampo.getText());
        eOcorrencia.setEmail(emailCampo.getText());
        eOcorrencia.setRelato(relatoCampo.getText());
        eOcorrencia.setComentario(comentarioCampo.getText());
        eOcorrencia.setProvidencia(providenciaCampo.getText());
        eOcorrencia.setDestinatario(destinatarioCampo.getText());
        eOcorrencia.setStatus((String) comboStatus.getSelectedItem());
        eOcorrencia.setCategoria(categoriaCampo.getText());

        nOcorrencias.alterar(eOcorrencia);
    }

    public void excluirOcorrencia() {
        if (idCampo.getText().equals("")) {
            try {
//                txtRa.setBorder(new LineBorder(Color.RED));
                JOptionPane.showMessageDialog(null, "Campo ID não preenchido!");
            } catch (Error e) {
            }
        } else {
            Object[] botoes = {"Sim", "Não"};
            int resposta = JOptionPane.showOptionDialog(null,
                    "Deseja realmente excluir o cadastro vinculado ao ID " + idCampo.getText() + " do paciente: " + nomeCampo.getText() + " ?",
                    "Confirmação", // o título da janela
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    botoes, botoes[0]);
            if (resposta == 0) {
                eOcorrencia = new EOcorrencia();
                eOcorrencia.setId(idCampo.getText());

                nOcorrencias.excluir(eOcorrencia);

            }
        }
    }

    private void buscarDados() throws SQLException {
        String buscaDados = "SELECT * from OCORRENCIA_ "
                + "WHERE id = " + "'" + idCampo.getText().trim() + "'";

//        System.out.println(buscaDados);
        ResultSet rs = statementPG.executeQuery(buscaDados);
//        limparCampos();
        if (!rs.next()) {
            JOptionPane.showMessageDialog(null, "Ocorrência não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
            idCampo.setText("");
            nomeCampo.setText("");
        } else {

//            Ocorrencia ocorrencia = new Ocorrencia();
//            comunicanteCampo.setText(ocorrencia.setComunicante(buscaDados));            
            comunicanteCampo.setText(rs.getString(9));
            regCampo.setText(rs.getString(1));
            nomeCampo.setText(rs.getString(2));
            comboOcorrencia.setSelectedItem(rs.getString(3));
            dataCampo.setText(rs.getString(4).trim().substring(8, 10)+rs.getString(4).trim().substring(5, 7)+rs.getString(4).trim().substring(0, 4));
            idCampo.setText(rs.getString(5));
            conclusaoCampo.setText(rs.getString(6).trim().substring(8, 10)+rs.getString(6).trim().substring(5, 7)+rs.getString(6).trim().substring(0, 4));
            celularCampo.setText(rs.getString(7));
            fixoCampo.setText(rs.getString(8));
            comunicanteCampo.setText(rs.getString(9));
            emailCampo.setText(rs.getString(10));
            relatoCampo.setText(rs.getString(11));
            comentarioCampo.setText(rs.getString(12));
            providenciaCampo.setText(rs.getString(13));
            comboStatus.setSelectedItem(rs.getString(14));
            destinatarioCampo.setText(rs.getString(15));
            categoriaCampo.setText(rs.getString(16));
//            idCampo.setEnabled(true);
            botaoExcluir.setEnabled(true);

        }
    }

    private void limparCampos() {
        regCampo.setText("");
        nomeCampo.setText("");
        comboOcorrencia.setSelectedIndex(0);
        dataCampo.setText("");
        idCampo.setText("");
        conclusaoCampo.setText("");
        celularCampo.setText("");
        fixoCampo.setText("");
        comunicanteCampo.setText("");
        emailCampo.setText("");
        relatoCampo.setText("");
        comentarioCampo.setText("");
        providenciaCampo.setText("");
        comboStatus.setSelectedIndex(0);
        destinatarioCampo.setText("");
    }

    private void desabilitarCampos() {
        regCampo.setEnabled(false);
        nomeCampo.setEnabled(false);
        comboOcorrencia.setEnabled(false);
        dataCampo.setEnabled(false);
        idCampo.setEnabled(false);
        conclusaoCampo.setEnabled(false);
        celularCampo.setEnabled(false);
        fixoCampo.setEnabled(false);
        comunicanteCampo.setEnabled(false);
        emailCampo.setEnabled(false);
        relatoCampo.setEnabled(false);
        comentarioCampo.setEnabled(false);
        providenciaCampo.setEnabled(false);
        comboStatus.setEnabled(false);
        destinatarioCampo.setEnabled(false);
    }

    private void habilitarCampos() {

        regCampo.setEnabled(true);
        nomeCampo.setEnabled(true);
        comboOcorrencia.setEnabled(true);
        dataCampo.setEnabled(true);
        idCampo.setEnabled(true);
        conclusaoCampo.setEnabled(true);
        celularCampo.setEnabled(true);
        fixoCampo.setEnabled(true);
        comunicanteCampo.setEnabled(true);
        emailCampo.setEnabled(true);
        relatoCampo.setEnabled(true);
        comentarioCampo.setEnabled(true);
        providenciaCampo.setEnabled(true);
        comboStatus.setEnabled(true);
        destinatarioCampo.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaPesquisaInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaPesquisaInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaPesquisaInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaPesquisaInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new TelaPesquisaInt().setVisible(true);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(TelaPesquisaInt.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (SQLException ex) {
//                    Logger.getLogger(TelaPesquisaInt.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaComunicante;
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoImprimir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JTextField categoriaCampo;
    private javax.swing.JTextField celularCampo;
    private javax.swing.JComboBox<String> comboOcorrencia;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JTextArea comentarioCampo;
    private javax.swing.JTextField comunicanteCampo;
    private javax.swing.JTextField conclusaoCampo;
    private javax.swing.JTextField dataCampo;
    private javax.swing.JTextField destinatarioCampo;
    private javax.swing.JTextField emailCampo;
    private javax.swing.JTextField fixoCampo;
    private javax.swing.JTextField idCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JTextArea providenciaCampo;
    private javax.swing.JTextField regCampo;
    private javax.swing.JTextArea relatoCampo;
    // End of variables declaration//GEN-END:variables
}
