package Telas;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import Conexao.DataBase;
import Conexao.DataBasePG;
import Metodos.NOcorrencias;
import Atributos.EOcorrencia;
import Metodos.NOcorrencias;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author jefersonrodrigues
 */
public class TelaCadastroInt extends javax.swing.JFrame {

    Statement statement;
    DataBasePG db = new DataBasePG();
    Connection con = db.getCon();

    private EOcorrencia eOcorrencia = null;
    private NOcorrencias nOcorrencias = new NOcorrencias();

    /**
     * Creates new form TelaOcorrencia
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public TelaCadastroInt() throws ClassNotFoundException, SQLException {
        initComponents();
        carregaId();
        statement = con.createStatement();
//        URL caminhoIcone = getClass().getResource("/Imagens/logoIcone.png");
//        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
//        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        categoriaCampo = new javax.swing.JTextField();
        idCampo = new javax.swing.JTextField();
        dataCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            dataCampo = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        comboOcorrencia = new javax.swing.JComboBox<>();
        conclusaoCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            conclusaoCampo = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        comunicanteCampo = new javax.swing.JTextField();
        celularCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##) # ####-####");
            celularCampo = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        fixoCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##) ####-####");
            fixoCampo = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        emailCampo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        relatoCampo = new javax.swing.JTextArea();
        relatoCampo.setLineWrap(true);
        jScrollPane2 = new javax.swing.JScrollPane();
        comentarioCampo = new javax.swing.JTextArea();
        comentarioCampo.setLineWrap(true);
        jScrollPane3 = new javax.swing.JScrollPane();
        providenciaCampo = new javax.swing.JTextArea();
        providenciaCampo.setLineWrap(true);
        destinatarioCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##) ####-####");
            fixoCampo = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        comboStatus = new javax.swing.JComboBox<>();
        botaoSalvar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRO DE OCORRÊNCIAS INTERNAS");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setText("Cadastro de Ocorrências");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nº Ocorrência:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Comunicante:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Telefone Cel:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Telefone Fixo:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Data:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Data para Conclusão:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("E-mail:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Relato:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Tipo de Ocorrência:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Comentário:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Status:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Providência:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Destinatário:");

        categoriaCampo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        categoriaCampo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        categoriaCampo.setText("INTERNA");
        categoriaCampo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        categoriaCampo.setEnabled(false);

        idCampo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCampoActionPerformed(evt);
            }
        });

        dataCampo.setToolTipText("");
        dataCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCampoActionPerformed(evt);
            }
        });

        comboOcorrencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "DENÚNCIA", "ELOGIO", "IMPROCEDENTE", "RECLAMAÇÃO", "SUGESTÃO" }));
        comboOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOcorrenciaActionPerformed(evt);
            }
        });

        conclusaoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclusaoCampoActionPerformed(evt);
            }
        });

        comunicanteCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comunicanteCampoActionPerformed(evt);
            }
        });

        celularCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularCampoActionPerformed(evt);
            }
        });

        fixoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixoCampoActionPerformed(evt);
            }
        });

        emailCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCampoActionPerformed(evt);
            }
        });

        relatoCampo.setColumns(10);
        relatoCampo.setRows(4);
        jScrollPane1.setViewportView(relatoCampo);

        comentarioCampo.setColumns(10);
        comentarioCampo.setRows(4);
        jScrollPane2.setViewportView(comentarioCampo);

        providenciaCampo.setColumns(10);
        providenciaCampo.setRows(4);
        jScrollPane3.setViewportView(providenciaCampo);

        destinatarioCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinatarioCampoActionPerformed(evt);
            }
        });

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "EM ANÁLISE", "ENCERRADO", "ENCAMINHADO", "PENDENTE" }));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        botaoSalvar.setText("SALVAR");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        botaoVoltar.setText("VOLTAR");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/limpar.png"))); // NOI18N
        botaoLimpar.setText("LIMPAR");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logovh.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(emailCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comunicanteCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(308, 308, 308)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(celularCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(261, 261, 261)
                                .addComponent(fixoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(conclusaoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(categoriaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(125, 125, 125)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(dataCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(botaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13)
                        .addComponent(jLabel16)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(320, 320, 320)
                            .addComponent(jLabel15))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(destinatarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(270, 270, 270)
                            .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(428, 428, 428))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(97, 97, 97)
                .addComponent(categoriaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conclusaoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(comunicanteCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celularCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fixoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel10)
                .addGap(5, 5, 5)
                .addComponent(emailCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel16)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinatarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comunicanteCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comunicanteCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comunicanteCampoActionPerformed

    private void celularCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularCampoActionPerformed

    private void fixoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fixoCampoActionPerformed

    private void dataCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCampoActionPerformed

    private void conclusaoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclusaoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conclusaoCampoActionPerformed

    private void emailCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCampoActionPerformed

    private void comboOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOcorrenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOcorrenciaActionPerformed

    private void idCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCampoActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        try {
            if (validarCampos()) {
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroInt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroInt.class.getName()).log(Level.SEVERE, null, ex);
        }
        limparCampos();
        desabilitarCampos();
//            carregaId();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
       TelaInicial tela = null;
        try {
            tela = new TelaInicial();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroInt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroInt.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        limparCampos();
        
        desabilitarCampos();
        botaoSalvar.setEnabled(false);
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void destinatarioCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinatarioCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinatarioCampoActionPerformed

    private void carregaId() throws SQLException {
        String queryString = "select MAX(id)+1 id from OCORRENCIA_";
        try (
                PreparedStatement ps = con.prepareStatement(queryString)) {
            ps.execute();
            ResultSet rs = ps.getResultSet();
            if (rs.next()) {
                idCampo.setText(rs.getString(1));
                idCampo.setEnabled(false);
            } if (idCampo.getText().isEmpty()) {
                idCampo.setText("1");
                idCampo.setEnabled(false);
            } else {
                idCampo.setEnabled(false);
                idCampo.setText(rs.getString(1));
            }
            rs.close();

        }

    }
    
    public boolean validarCampos() throws SQLException, ClassNotFoundException {
        if (dataCampo.getText().equals("  /  /    ")){
            dataCampo.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Preencha o Campo Obrigatório!");
            return true;
        } else if (conclusaoCampo.getText().equals("  /  /    ")){
            dataCampo.setBorder(new LineBorder(Color.GRAY));
            conclusaoCampo.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Preencha o Campo Obrigatório!");
            return true;
        }else{
//            dataCampo.setBorder(new LineBorder(Color.GRAY));
            conclusaoCampo.setBorder(new LineBorder(Color.GRAY));
            incluiBD();
            return false;
        }
    }

    private void incluiBD() throws SQLException, ClassNotFoundException {
       if (dataCampo.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Campo não preenchido!" + "\nDATA");
        } else if (conclusaoCampo.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Campo não preenchido!" + "\nDATA DE CONCLUSÃO");
        } else {
        eOcorrencia = new EOcorrencia();
        eOcorrencia.setId(idCampo.getText());
        eOcorrencia.setData(dataCampo.getText().substring(6, 10)+"-"+dataCampo.getText().substring(3, 5)+"-"+dataCampo.getText().substring(0, 2));
        eOcorrencia.setOcorrencia((String) comboOcorrencia.getSelectedItem());
        eOcorrencia.setConclusao(conclusaoCampo.getText().substring(6, 10)+"-"+conclusaoCampo.getText().substring(3, 5)+"-"+conclusaoCampo.getText().substring(0, 2));
        eOcorrencia.setComunicante(comunicanteCampo.getText());
        eOcorrencia.setCelular(celularCampo.getText());
        eOcorrencia.setFixo(fixoCampo.getText());
        eOcorrencia.setEmail(emailCampo.getText());
        eOcorrencia.setRelato(relatoCampo.getText());
        eOcorrencia.setComentario(comentarioCampo.getText());
        eOcorrencia.setProvidencia(providenciaCampo.getText());
        eOcorrencia.setStatus((String) comboStatus.getSelectedItem());
        eOcorrencia.setCategoria(categoriaCampo.getText());
        eOcorrencia.setDestinatario(destinatarioCampo.getText());

        nOcorrencias.incluirInt(eOcorrencia);
        carregaId();
        }
    }

    private void limparCampos() {
        comboOcorrencia.setSelectedIndex(0);
//        dataCampo.setText("");
//        idCampo.setText("");
        conclusaoCampo.setText("");
        celularCampo.setText("");
        fixoCampo.setText("");
        comunicanteCampo.setText("");
        emailCampo.setText("");
        relatoCampo.setText("");
        comentarioCampo.setText("");
        providenciaCampo.setText("");
        comboStatus.setSelectedIndex(0);
        destinatarioCampo.setText("");
    }

    private void desabilitarCampos() {
        comboOcorrencia.setEnabled(false);
        dataCampo.setEnabled(false);
        idCampo.setEnabled(false);
        conclusaoCampo.setEnabled(false);
        celularCampo.setEnabled(false);
        fixoCampo.setEnabled(false);
        comunicanteCampo.setEnabled(false);
        emailCampo.setEnabled(false);
        relatoCampo.setEnabled(false);
        comentarioCampo.setEnabled(false);
        providenciaCampo.setEnabled(false);
        comboStatus.setEnabled(false);
        destinatarioCampo.setEnabled(false);
        
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//
//        /* Create and display the form */
//
//        java.awt.EventQueue.invokeLater(() -> {
//            try {
//                TelaCadastroInt t;
//                t = new TelaCadastroInt();
//                t.setVisible(true);
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(TelaCadastroInt.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField categoriaCampo;
    private javax.swing.JTextField celularCampo;
    private javax.swing.JComboBox<String> comboOcorrencia;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JTextArea comentarioCampo;
    private javax.swing.JTextField comunicanteCampo;
    private javax.swing.JTextField conclusaoCampo;
    private javax.swing.JTextField dataCampo;
    private javax.swing.JTextField destinatarioCampo;
    private javax.swing.JTextField emailCampo;
    private javax.swing.JTextField fixoCampo;
    private javax.swing.JTextField idCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea providenciaCampo;
    private javax.swing.JTextArea relatoCampo;
    // End of variables declaration//GEN-END:variables
}
