package Telas;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Conexao.DataBase;
import Conexao.DataBasePG;
import Atributos.EOcorrencia;
import Metodos.NOcorrencias;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.DateFormat;
import java.text.Format;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.border.LineBorder;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author jefersonrodrigues
 */
public class TelaCadastroExt extends javax.swing.JFrame {

    Statement statementPG, statementSS;
    DataBase db = new DataBase();
    DataBasePG db2 = new DataBasePG();
    Connection con = db.getCon();
    Connection con2 = db2.getCon();

    Vector<String> listaLimpa = new Vector<>();
    Date data;

    private EOcorrencia eOcorrencia = null;
    private NOcorrencias nOcorrencias = new NOcorrencias();

    /**
     * Creates new form TelaOcorrencia
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public TelaCadastroExt() throws ClassNotFoundException, SQLException {
        initComponents();
        carregaId();
        statementSS = con.createStatement();
        statementPG = con2.createStatement();

//        URL caminhoIcone = getClass().getResource("/Imagens/logoIcone.png");
//        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
//        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        reg = new javax.swing.JLabel();
        nomeCampo = new javax.swing.JTextField();
        comboOcorrencia = new javax.swing.JComboBox<>();
        dataCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            dataCampo = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        idCampo = new javax.swing.JTextField();
        conclusaoCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            conclusaoCampo = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        comunicanteCampo = new javax.swing.JTextField();
        celularCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##) # ####-####");
            celularCampo = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        fixoCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##) ####-####");
            fixoCampo = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        emailCampo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        relatoCampo = new javax.swing.JTextArea();
        relatoCampo.setLineWrap(true);
        jScrollPane2 = new javax.swing.JScrollPane();
        comentarioCampo = new javax.swing.JTextArea();
        comentarioCampo.setLineWrap(true);
        jScrollPane3 = new javax.swing.JScrollPane();
        providenciaCampo = new javax.swing.JTextArea();
        providenciaCampo.setLineWrap(true);
        destinatarioCampo = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##) ####-####");
            fixoCampo = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        comboStatus = new javax.swing.JComboBox<>();
        botaoSalvar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        campoPesquisa = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaPacientes = new javax.swing.JList<>();
        categoriaCampo = new javax.swing.JTextField();
        regCampo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        checkPaciente = new javax.swing.JCheckBox();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRO DE OCORRÊNCIAS EXTERNAS");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setText("Cadastro de Ocorrências");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nº Ocorrência:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Comunicante:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Paciente / ID:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Telefone Cel:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Telefone Fixo:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Data:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Data para Conclusão:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("E-mail:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Relato:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Tipo de Ocorrência:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Comentário:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Status:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Providência:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Destinatário:");

        reg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reg.setText("Registro:");

        nomeCampo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeCampo.setEnabled(false);
        nomeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCampoActionPerformed(evt);
            }
        });

        comboOcorrencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "DENÚNCIA", "ELOGIO", "IMPROCEDENTE", "RECLAMAÇÃO", "SUGESTÃO" }));
        comboOcorrencia.setEnabled(false);
        comboOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOcorrenciaActionPerformed(evt);
            }
        });

        dataCampo.setToolTipText("");
        dataCampo.setEnabled(false);
        dataCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCampoActionPerformed(evt);
            }
        });

        idCampo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCampoActionPerformed(evt);
            }
        });

        conclusaoCampo.setEnabled(false);
        conclusaoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclusaoCampoActionPerformed(evt);
            }
        });

        comunicanteCampo.setEnabled(false);
        comunicanteCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comunicanteCampoActionPerformed(evt);
            }
        });

        celularCampo.setEnabled(false);
        celularCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularCampoActionPerformed(evt);
            }
        });

        fixoCampo.setEnabled(false);
        fixoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixoCampoActionPerformed(evt);
            }
        });

        emailCampo.setEnabled(false);
        emailCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCampoActionPerformed(evt);
            }
        });

        relatoCampo.setColumns(10);
        relatoCampo.setRows(5);
        relatoCampo.setEnabled(false);
        jScrollPane1.setViewportView(relatoCampo);

        comentarioCampo.setColumns(10);
        comentarioCampo.setRows(5);
        comentarioCampo.setEnabled(false);
        jScrollPane2.setViewportView(comentarioCampo);

        providenciaCampo.setColumns(10);
        providenciaCampo.setRows(5);
        providenciaCampo.setEnabled(false);
        jScrollPane3.setViewportView(providenciaCampo);

        destinatarioCampo.setEnabled(false);
        destinatarioCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinatarioCampoActionPerformed(evt);
            }
        });

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "EM ANÁLISE", "ENCERRADO", "ENCAMINHADO", "PENDENTE" }));
        comboStatus.setEnabled(false);
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        botaoSalvar.setText("SALVAR");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        botaoVoltar.setText("VOLTAR");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/limpar.png"))); // NOI18N
        botaoLimpar.setText("LIMPAR");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        campoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPesquisaKeyReleased(evt);
            }
        });

        ListaPacientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "", "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaPacientesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(ListaPacientes);

        categoriaCampo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        categoriaCampo.setText("EXTERNA");
        categoriaCampo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        categoriaCampo.setEnabled(false);

        regCampo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        regCampo.setEnabled(false);
        regCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCampoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logovh.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Digite o nome do paciente que deseja pesquisar:");

        checkPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPaciente.setText("Paciente não informado");
        checkPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(comunicanteCampo)
                            .addComponent(reg)
                            .addComponent(regCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(nomeCampo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(idCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(comboOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(conclusaoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(celularCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(151, 151, 151)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fixoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel10)
                            .addComponent(emailCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(categoriaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(checkPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(botaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(destinatarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(385, 385, 385))
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoriaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkPaciente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conclusaoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comunicanteCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fixoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(celularCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(destinatarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comunicanteCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comunicanteCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comunicanteCampoActionPerformed

    private void nomeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCampoActionPerformed

    private void celularCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularCampoActionPerformed

    }//GEN-LAST:event_celularCampoActionPerformed

    private void fixoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fixoCampoActionPerformed

    private void dataCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCampoActionPerformed

    private void conclusaoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclusaoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conclusaoCampoActionPerformed

    private void emailCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCampoActionPerformed

    private void comboOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOcorrenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOcorrenciaActionPerformed

    private void idCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCampoActionPerformed

    private void regCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regCampoActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        
        try {
            if (validarCampos()) {
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroExt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroExt.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        limparCampos();
        desabilitarCampos();
//            carregaId();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        TelaInicial tela = null;
        try {
            tela = new TelaInicial();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroExt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroExt.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void campoPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisaKeyReleased
        try {
            buscarDados();

        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_campoPesquisaKeyReleased

    private void ListaPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaPacientesMouseClicked
        if (campoPesquisa.getText().isEmpty()) {

        } else {
            regCampo.setText(ListaPacientes.getSelectedValue().split(" - ")[0]);
            try {
                buscaPaciente();
            } catch (SQLException ex) {
                Logger.getLogger(TelaCadastroExt.class.getName()).log(Level.SEVERE, null, ex);
            }
            ListaPacientes.setListData(listaLimpa);
            campoPesquisa.setText("");
//        botaoAlterar.setEnabled(true);
        }
    }//GEN-LAST:event_ListaPacientesMouseClicked

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        limparCampos();
        desabilitarCampos();
        botaoSalvar.setEnabled(false);
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void destinatarioCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinatarioCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinatarioCampoActionPerformed

    private void checkPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPacienteActionPerformed

        if (checkPaciente.isSelected()) {
            regCampo.setText("0");
            nomeCampo.setText("PACIENTE NÃO INFORMADO");
            regCampo.setEnabled(false);
            idCampo.setEnabled(false);
            nomeCampo.setEnabled(true);
            dataCampo.setEnabled(true);
            comboOcorrencia.setEnabled(true);
            conclusaoCampo.setEnabled(true);
            comunicanteCampo.setEnabled(true);
            celularCampo.setEnabled(true);
            fixoCampo.setEnabled(true);
            emailCampo.setEnabled(true);
            relatoCampo.setEnabled(true);
            comentarioCampo.setEnabled(true);
            comboStatus.setEnabled(true);
            providenciaCampo.setEnabled(true);
            destinatarioCampo.setEnabled(true);
            nomeCampo.setEnabled(false);
            botaoSalvar.setEnabled(true);
        } else {
            regCampo.setText("");
            nomeCampo.setText("");
            regCampo.setEnabled(false);
            idCampo.setEnabled(false);
            nomeCampo.setEnabled(false);

            nomeCampo.setEnabled(false);
            dataCampo.setEnabled(false);
            comboOcorrencia.setEnabled(false);
            conclusaoCampo.setEnabled(false);
            comunicanteCampo.setEnabled(false);
            celularCampo.setEnabled(false);
            fixoCampo.setEnabled(false);
            emailCampo.setEnabled(false);
            relatoCampo.setEnabled(false);
            comentarioCampo.setEnabled(false);
            comboStatus.setEnabled(false);
            providenciaCampo.setEnabled(false);
            destinatarioCampo.setEnabled(false);

            botaoSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_checkPacienteActionPerformed

    private void buscarDados() throws SQLException {
        ListaPacientes.setListData(listaLimpa);
        if (!campoPesquisa.getText().isEmpty()) {
            if (campoPesquisa.getText().length() > 2) {
//            String queryString = "SELECT * from OCORRENCIA_ WHERE PACIENTE LIKE '%" + campoPesquisa.getText() + "%'";
                String queryString = "SELECT PAC.PAC_REG, PAC.PAC_NOME, PAC. PAC_NOME_MAE\n"
                        + " FROM PAC\n"
                        + " WHERE ( PAC.PAC_NOME LIKE '" + campoPesquisa.getText().trim() + "%')";
                ResultSet rs = statementSS.executeQuery(queryString);
                Vector<String> listModel = new Vector<>(10);
                if (rs.next()) {
                    do {
//                    listModel.add(rs.getString(5) + "  -  " + rs.getString(2) + "  -  " + rs.getString(9).trim());
                        listModel.add(rs.getString(1) + " - " + rs.getString(2).trim() + "  -  " + rs.getString(3));
//                            + "  -  "+ rs.getString(3).trim());
//                     +"  -  "+ rs.getString(4).trim() +"  -  "+ rs.getString(5).trim() +"  -  "+ rs.getString(6).trim()
//                     +"  -  "+ rs.getString(7).trim() +"  -  "+ rs.getString(8).trim() +"  -  "+ rs.getString(9).trim()
//                     +"  -  "+ rs.getString(10).trim() +"  -  "+ rs.getString(11).trim() +"  -  "+ rs.getString(12).trim()
//                     +"  -  "+ rs.getString(13).trim() +"  -  "+ rs.getString(14).trim());
                    } while (rs.next());
                }
                ListaPacientes.setListData(listModel);

            }
        }

    }

    private void buscaPaciente() throws SQLException {
        if (regCampo.getText().equals("")) {
            try {
                JOptionPane.showMessageDialog(null, "Campo REGISTRO em branco, \n Favor informar o registro do Paciente!");
            } catch (Error e) {
            }
        } else {
            String queryString = "SELECT PAC.PAC_NOME\n"
                    + " FROM PAC\n"
                    + " WHERE ( PAC.PAC_REG = '" + regCampo.getText().trim() + "')";
            ResultSet rs = statementSS.executeQuery(queryString);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "Paciente não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                regCampo.setText("");
                nomeCampo.setText("");
            } else {
                nomeCampo.setText(rs.getString(1));
                regCampo.setEnabled(false);
                idCampo.setEnabled(false);
                nomeCampo.setEnabled(true);
                dataCampo.setEnabled(true);
                comboOcorrencia.setEnabled(true);
                conclusaoCampo.setEnabled(true);
                comunicanteCampo.setEnabled(true);
                celularCampo.setEnabled(true);
                fixoCampo.setEnabled(true);
                emailCampo.setEnabled(true);
                relatoCampo.setEnabled(true);
                comentarioCampo.setEnabled(true);
                comboStatus.setEnabled(true);
                providenciaCampo.setEnabled(true);
                destinatarioCampo.setEnabled(true);
                nomeCampo.setEnabled(false);
                botaoSalvar.setEnabled(true);
            }
        }
    }

    private void carregaId() throws SQLException {
        String queryString = "select MAX(id)+1 id from OCORRENCIA_";
        try (
                PreparedStatement ps = con2.prepareStatement(queryString)) {
            ps.execute();
            ResultSet rs = ps.getResultSet();
            if (rs.next()) {
                idCampo.setText(rs.getString(1));
                idCampo.setEnabled(false);
            }
            if (idCampo.getText().isEmpty()) {
                idCampo.setText("1");
                idCampo.setEnabled(false);
            } else {
                idCampo.setEnabled(false);
                idCampo.setText(rs.getString(1));
            }
            rs.close();

        }

    }
    
    public boolean validarCampos() throws SQLException, ClassNotFoundException {
        if (dataCampo.getText().equals("  /  /    ")){
            dataCampo.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Preencha o Campo Obrigatório!");
            return true;
        } else if (conclusaoCampo.getText().equals("  /  /    ")){
            dataCampo.setBorder(new LineBorder(Color.GRAY));
            conclusaoCampo.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Preencha o Campo Obrigatório!");
            return true;
        }else{
//            dataCampo.setBorder(new LineBorder(Color.GRAY));
            conclusaoCampo.setBorder(new LineBorder(Color.GRAY));
            incluiBD();
            return false;
        }
    }

    private void incluiBD() throws SQLException, ClassNotFoundException {
            eOcorrencia = new EOcorrencia();
            eOcorrencia.setRegistro(regCampo.getText());
            eOcorrencia.setPaciente(nomeCampo.getText().trim());
            eOcorrencia.setOcorrencia((String) comboOcorrencia.getSelectedItem());
            eOcorrencia.setData(dataCampo.getText().substring(6, 10) + "-" + dataCampo.getText().substring(3, 5) + "-" + dataCampo.getText().substring(0, 2));
            eOcorrencia.setId(idCampo.getText());
            eOcorrencia.setConclusao(conclusaoCampo.getText().substring(6, 10) + "-" + conclusaoCampo.getText().substring(3, 5) + "-" + conclusaoCampo.getText().substring(0, 2));
            eOcorrencia.setComunicante(comunicanteCampo.getText().trim());
            eOcorrencia.setCelular(celularCampo.getText());
            eOcorrencia.setFixo(fixoCampo.getText());
            eOcorrencia.setEmail(emailCampo.getText());
            eOcorrencia.setRelato(relatoCampo.getText());
            eOcorrencia.setComentario(comentarioCampo.getText());
            eOcorrencia.setProvidencia(providenciaCampo.getText());
            eOcorrencia.setStatus((String) comboStatus.getSelectedItem());
            eOcorrencia.setCategoria(categoriaCampo.getText());
            eOcorrencia.setDestinatario(destinatarioCampo.getText());
            nOcorrencias.incluirExt(eOcorrencia);

            carregaId();
    }

    private void limparCampos() {
        regCampo.setText("");
        nomeCampo.setText("");
        comboOcorrencia.setSelectedIndex(0);
        dataCampo.setText("");
        conclusaoCampo.setText("");
        celularCampo.setText("");
        fixoCampo.setText("");
        comunicanteCampo.setText("");
        emailCampo.setText("");
        relatoCampo.setText("");
        comentarioCampo.setText("");
        providenciaCampo.setText("");
        comboStatus.setSelectedIndex(0);
        destinatarioCampo.setText("");
    }

    private void desabilitarCampos() {
        regCampo.setEnabled(false);
        nomeCampo.setEnabled(false);
        comboOcorrencia.setEnabled(false);
        dataCampo.setEnabled(false);
        idCampo.setEnabled(false);
        conclusaoCampo.setEnabled(false);
        celularCampo.setEnabled(false);
        fixoCampo.setEnabled(false);
        comunicanteCampo.setEnabled(false);
        emailCampo.setEnabled(false);
        relatoCampo.setEnabled(false);
        comentarioCampo.setEnabled(false);
        providenciaCampo.setEnabled(false);
        comboStatus.setEnabled(false);
        destinatarioCampo.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            try {
//                TelaCadastroExt t;
//                t = new TelaCadastroExt();
//                t.setVisible(true);
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(TelaCadastroExt.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaPacientes;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JTextField categoriaCampo;
    private javax.swing.JTextField celularCampo;
    private javax.swing.JCheckBox checkPaciente;
    private javax.swing.JComboBox<String> comboOcorrencia;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JTextArea comentarioCampo;
    private javax.swing.JTextField comunicanteCampo;
    private javax.swing.JTextField conclusaoCampo;
    private javax.swing.JTextField dataCampo;
    private javax.swing.JTextField destinatarioCampo;
    private javax.swing.JTextField emailCampo;
    private javax.swing.JTextField fixoCampo;
    private javax.swing.JTextField idCampo;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JTextArea providenciaCampo;
    private javax.swing.JLabel reg;
    public javax.swing.JTextField regCampo;
    private javax.swing.JTextArea relatoCampo;
    // End of variables declaration//GEN-END:variables
}
